### ISSUE TITLE
Not sure how to get beyond this error

### ISSUE THREAD

**Issue by disruptivepatternmaterial** [tclayson/node-red-contrib-google-vision-object-detection#2]
"Error: The incoming JSON object does not contain a client_email field"

I tried adding it in the inbound msg in a few ways, but not sure how to fix this.

**Comment by tclayson** [comment]
Hi @ntableman, it sounds like the service account key from Google isn't right? Have a look here https://cloud.google.com/iam/docs/creating-managing-service-account-keys

The format of the service account key json should be:

`{
  "type": "service_account",
  "project_id": "project-id",
  "private_key_id": "key-id",
  "private_key": "-----BEGIN PRIVATE KEY-----\nprivate-key\n-----END PRIVATE KEY-----\n",
  "client_email": "service-account-email",
  "client_id": "client-id",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/service-account-email"
}`

It sounds like your service account key doesn't have a `client_email` field (and maybe others are also missing).

Let me know how you get on.
