### ISSUE TITLE
No localizedObjectAnnotations returned

### ISSUE THREAD

**Issue by bbordelon** [tclayson/node-red-contrib-google-vision-object-detection#5]
The localizedObjectAnnotations consistently returns an empty array for images, but when those same images are tested on the Google try-it site (https://cloud.google.com/vision/docs/drag-and-drop), it yields valid localizedObjectAnnotations data.

Here is an example image:
![vapi](https://user-images.githubusercontent.com/10342848/177404579-1733b7da-6463-4505-9941-3d88404219eb.jpg)
Here's what the Google try-it site yields:
![Untitled](https://user-images.githubusercontent.com/10342848/177405920-8a7e8610-8b92-4dca-b12b-64be4a4ef8bf.jpg)

And here's the relevant JSON from their site (let me know if there's a better way to display JSON, sorry):
`{
  "localizedObjectAnnotations": [
    {
      "boundingPoly": {
        "normalizedVertices": [
          {
            "x": 0.7117261,
            "y": 0.04932441
          },
          {
            "x": 0.8325145,
            "y": 0.04932441
          },
          {
            "x": 0.8325145,
            "y": 0.16607776
          },
          {
            "x": 0.7117261,
            "y": 0.16607776
          }
        ]
      },
      "mid": "/m/03jm5",
      "name": "House",
      "score": 0.658528
    },
    {
      "boundingPoly": {
        "normalizedVertices": [
          {
            "x": 0.52676576,
            "y": 0.17107202
          },
          {
            "x": 0.6742304,
            "y": 0.17107202
          },
          {
            "x": 0.6742304,
            "y": 0.27514836
          },
          {
            "x": 0.52676576,
            "y": 0.27514836
          }
        ]
      },
      "mid": "/m/0k4j",
      "name": "Car",
      "score": 0.5975173
    },
    {
      "boundingPoly": {
        "normalizedVertices": [
          {
            "x": 0.34041405,
            "y": 0.00006405304
          },
          {
            "x": 0.46132672,
            "y": 0.00006405304
          },
          {
            "x": 0.46132672,
            "y": 0.107189775
          },
          {
            "x": 0.34041405,
            "y": 0.107189775
          }
        ]
      },
      "mid": "/m/03jm5",
      "name": "House",
      "score": 0.58679444
    },
    {
      "boundingPoly": {
        "normalizedVertices": [
          {
            "x": 0.4540988,
            "y": 0.0086902315
          },
          {
            "x": 0.56552285,
            "y": 0.0086902315
          },
          {
            "x": 0.56552285,
            "y": 0.10638702
          },
          {
            "x": 0.4540988,
            "y": 0.10638702
          }
        ]
      },
      "mid": "/m/03jm5",
      "name": "House",
      "score": 0.5409888
    },
    {
      "boundingPoly": {
        "normalizedVertices": [
          {
            "x": 0.08924377,
            "y": 0.032218922
          },
          {
            "x": 0.21381605,
            "y": 0.032218922
          },
          {
            "x": 0.21381605,
            "y": 0.17661925
          },
          {
            "x": 0.08924377,
            "y": 0.17661925
          }
        ]
      },
      "mid": "/m/03jm5",
      "name": "House",
      "score": 0.50383097
    }
  ]
}
`

The other detections appear to work, and return essentially the same data as on the Google test page.
[Apologies for any style or etiquette breaches on my part. It's the first time I've raised an issue on GitHub.]

**Comment by bbordelon** [comment]
@tclayson is this project something you still work on? Just came back around to use this again and remembered that the localizedObjectAnnotations doesn't return any values.
Thanks.

**Comment by tclayson** [comment]
Hi @bbordelon ,

I'm sorry, I did not see your previous message as I am not actively monitoring this repo.

I just installed everything from scratch and it seems to be working fine for me. When using the image that you put in your message above I get the following:

![image](https://user-images.githubusercontent.com/1427413/216058776-955b1080-9152-436f-a9c3-9ddc87e70759.png)

Are you getting any errors at all in node red? Have you set your service account up correctly with billing enabled and the Vision API enabled?

Here is my Node-Red flow:

```
[
    {
        "id": "70d78f0c.daa64",
        "type": "google-vision-object-detection",
        "z": "cd602255617a8714",
        "keyFilename": "/Users/thomas.clayson/Downloads/home-assistant-215118-f296c43f2b05.json",
        "name": "",
        "x": 570,
        "y": 360,
        "wires": [
            [
                "c388a09c.42d5"
            ]
        ]
    },
    {
        "id": "13344e52.cd82a2",
        "type": "http request",
        "z": "cd602255617a8714",
        "name": "",
        "method": "GET",
        "ret": "bin",
        "paytoqs": "ignore",
        "url": "https://user-images.githubusercontent.com/10342848/177404579-1733b7da-6463-4505-9941-3d88404219eb.jpg",
        "tls": "",
        "persist": false,
        "proxy": "",
        "insecureHTTPParser": false,
        "authType": "",
        "senderr": false,
        "headers": [],
        "x": 370,
        "y": 360,
        "wires": [
            [
                "70d78f0c.daa64"
            ]
        ]
    },
    {
        "id": "8ccef21c.f0f1b",
        "type": "inject",
        "z": "cd602255617a8714",
        "name": "",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 180,
        "y": 360,
        "wires": [
            [
                "13344e52.cd82a2"
            ]
        ]
    },
    {
        "id": "c388a09c.42d5",
        "type": "debug",
        "z": "cd602255617a8714",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "x": 770,
        "y": 360,
        "wires": []
    }
]
```

**Comment by bbordelon** [comment]
OMG I'm a complete idiot, sorry @tclayson!  I'm actually using the vision API node from the GCP code (node-red-contrib-google-cloud).  When it was failing to return object localizations my first search result brought me to yours, not theirs.
The **good** news is that yours works!  So I'll probably use yours instead :) 
(theirs has an open issue about the object localizations already)
Again, my apologies, and thank you for the response!

**Comment by tclayson** [comment]
Ha! No problem. Please enjoy this plugin, let me know if you come across any other issues :)
